### ISSUE TITLE
Erreurs dans les logs

### ISSUE THREAD

**Issue by obigroup** [cozy/cozy-data-system#139]
Bonjour,

J'ai des erreurs dans les logs de mon app data-system cependant mon application fonctionne très bien... (Pour chaque actions d'ajouts (ajout d'un fichier ou dans le calendrier...) dans cozy cela rajoute un bloque de log).
Je ne comprend pas comment le data-system peut fonctionner alors que dans les erreurs il est indiqué : 

```
[2015-04-10 22:01:33:748] error - app:error | Application is not authorized
[2015-04-10 22:01:33:748] error - app:error | Error: Application is not authorized
    at /usr/local/cozy/apps/data-system/build/server/helpers/utils.js:29:13
    at /usr/local/cozy/apps/data-system/build/server/lib/token.js:43:22
    at checkToken (/usr/local/cozy/apps/data-system/build/server/lib/token.js:22:14)
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/build/server/lib/token.js:33:12)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/build/server/helpers/utils.js:23:10)
    at Object.module.exports.checkPermissionsByType [as handle] (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:61:10)
    at next_layer (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at param (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/index.js:303:14)
[2015-04-10 22:01:33:896] error - app:error | Application is not authenticated
[2015-04-10 22:01:33:897] error - app:error | Error: Application is not authenticated
    at /usr/local/cozy/apps/data-system/build/server/helpers/utils.js:25:13
    at /usr/local/cozy/apps/data-system/build/server/lib/token.js:49:18
    at checkToken (/usr/local/cozy/apps/data-system/build/server/lib/token.js:24:14)
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/build/server/lib/token.js:33:12)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/build/server/helpers/utils.js:23:10)
    at Object.module.exports.checkPermissionsByDoc [as handle] (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:53:10)
    at next_layer (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Object.callback (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:38:14)
    at /usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/database/documents.js:45:18
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:235:9)
[2015-04-10 22:01:33:917] error - app:error | Application is not authenticated
[2015-04-10 22:01:33:918] error - app:error | Error: Application is not authenticated
    at /usr/local/cozy/apps/data-system/build/server/helpers/utils.js:25:13
    at /usr/local/cozy/apps/data-system/build/server/lib/token.js:49:18
    at checkToken (/usr/local/cozy/apps/data-system/build/server/lib/token.js:24:14)
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/build/server/lib/token.js:33:12)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/build/server/helpers/utils.js:23:10)
    at Object.module.exports.checkPermissionsByDoc [as handle] (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:53:10)
    at next_layer (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Object.callback (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:38:14)
    at /usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/database/documents.js:45:18
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:235:9)
```
Merci d'avance de vos éclaircissements.

**Comment by jsilvestre** [comment]
Bonjour,
Cette erreur survient lorsqu'une application requête le Data System sur un doctype pour lequel elle n'a pas la permission.
Je vous suggère cet [élément de documentation](http://cozy.io/en/hack/cookbooks/authentication-authorization-workflows.html#applications-authentication-and-permissions) qui explique le mécanisme en détail.

Concernant votre problème en particulier, toutes les requêtes au Data System semblent concernées. Pouvez-vous le confirmer ? Le Data System est-il bien démarré avec la variable d'environnement `NODE_ENV=production` ?

**Comment by obigroup** [comment]
Bonjour @jsilvestre ,

Effectivement cela concerne toutes le requêtes au Data System.
Il est bien démarré en NODE_ENV=production.
Le Data System fonctionne quand même, comment cela est il possible ?

Merci.

**Comment by frankrousseau** [comment]
@poupotte If you find time can you have a look this issue?

**Comment by poupotte** [comment]
Je n'arrive pas à reproduire ce bug. 
@obigroup , pouvez me fournir les retours de `cozy-monitor versions` dans votre Cozy ? 
Cette erreur est affichée sur la totalité des requêtes du data-system ou sur toutes les requêtes d'ajout ?

**Comment by obigroup** [comment]
@poupotte voici ma version de cozy-monitor : 1.2.19

Cette erreur est affichée sur la totalité des requêtes du data-system ou sur toutes les requêtes d'ajout ? <= Lors de l'installation d'un module, mais aussi sur des actions de suppressions de fichiers dans l'apli Files, des fois à des moments ou je ne fais rien...

Je rencontre d'autres problèmes peut être lié à cela : 
Quand je supprime un fichier que j'avais déjà envoyé une fois et supprimé une fois j'ai : 
```
error - feed | {"name":"CouchError","message":"conflict: Document update conflict.","error":"conflict","reason":"Document update conflict.","headers":{"server":"CouchDB/1.2.0 (Erlang OTP/R15B01)","date":"Mon, 13 Apr 2015 11:36:08 GMT","content-type":"text/plain; charset=utf-8","content-length":"58","cache-control":"must-revalidate","status":409}}
```

**Comment by poupotte** [comment]
Pardon, je me suis mal exprimée, j'aimerai avoir l'ensemble des versions de vos applications dans cozy que l'on peut les récupérer via la ligne de commande `cozy-monitor versions` et non juste la version du monitor

**Comment by obigroup** [comment]
Voici : 

Cozy Stack:
controller: 2.0.22
data-system: 1.0.27
home: 1.0.41
proxy: 1.0.13
indexer: 1.0.0
monitor: 1.2.19

Other applications: 
calendar: 1.0.13
contacts: 1.1.3
files: 1.1.4
photos: 1.0.10
sync: 1.0.6

**Comment by obigroup** [comment]
ping @poupotte

**Comment by poupotte** [comment]
Bonjour @obigroup, 

Votre plate-forme est bien à jour. Je ne comprend pas pourquoi vous avez toutes ces erreurs. 

Est-ce que vous pourriez afficher les identifiants envoyés par vos applications au data-system (ça correspond au username et password [ici](https://github.com/cozy/cozy-data-system/blob/master/server/lib/token.coffee#L22)) et les comparer avec le slug et token stockés en base de données (dans les documents correspondant à vos applications) ?

**Comment by obigroup** [comment]
@poupotte J'ai trouvé d'où provenait le problème. J'avais 2 instances du controller qui tournaient en même temps donc l'une des deux n'avait pas les bons accès.

Vous pouvez clôturer le ticket.
Merci.

**Comment by poupotte** [comment]
Ah, je comprend mieux, je n'arrivais vraiment pas à voir comment c'était possible. Merci pour votre retour.
