### ISSUE TITLE
Server crash: stream has no method setHeader

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#151]
Data system of a user's instance keep crashing, here are the logs:

```
/usr/local/cozy/apps/data-system/build/server/controllers/attachments.js:86
        stream.setHeader('range', req.headers['range']);
               ^
TypeError: Object #<IncomingMessage> has no method 'setHeader'
    at /usr/local/cozy/apps/data-system/build/server/controllers/attachments.js:86:16
    at callback (/usr/local/cozy/apps/data-system/build/server/lib/downloader.js:47:7)
    at ClientRequest.<anonymous> (/usr/local/cozy/apps/data-system/build/server/lib/downloader.js:81:20)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData [as ondata] (http.js:1584:20)
    at TCP.onread (net.js:528:27)

```

**Comment by frankrousseau** [comment]
Can you push the build and make a PR on the master branch?
