### ISSUE TITLE
Server error: TypeError: Cannot read property 'docType' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#189]
Seen in server logs:
```
[2016-01-04 22:35:20:433] info - helper/db_feed | Publishing usage.application mon-telephone
[Mon, 04 Jan 2016 22:35:20 GMT] - GET /replication/_local/0Asqf.FrJMMnLNIRgJptvw%3D%3D?&_nonce=1451946918585 - 200 - 5.339 ms -  522
[2016-01-04 22:35:20:480] info - helper/db_feed | Publishing usage.application mon-telephone
[2016-01-04 22:35:20:482] info - helper/db_feed | Publishing usage.application mon-telephone
[Mon, 04 Jan 2016 22:35:20 GMT] - POST /replication/_bulk_docs?_nonce=1451946918624 - 201 - 6.457 ms -  67
[2016-01-04 22:35:20:575] info - helper/db_feed | Publishing usage.application mon-telephone
[Mon, 04 Jan 2016 22:35:20 GMT] - GET /replication/_local/0Asqf.FrJMMnLNIRgJptvw%3D%3D?&_nonce=1451946918728 - 200 - 4.944 ms -  522
[2016-01-04 22:35:20:694] info - helper/db_feed | Publishing usage.application mon-telephone
[Mon, 04 Jan 2016 22:35:20 GMT] - POST /replication/_revs_diff?_nonce=1451946918846 - 200 - 7.105 ms -  92

TypeError: Cannot read property 'docType' of undefined
    at Object.callback (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:80:43)
    at /usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/database/documents.js:45:18
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:232:20)
    at Request.self.callback (/usr/local/cozy/apps/data-system/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

```

**Comment by poupotte** [comment]
This issue should be fixed.
