### ISSUE TITLE
Server crash when a document has no view

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#202]
Seen on the server of @kosssi. Seems related to mobile replication. Don't know if it is a “normal” case, but I'll just add some defensive code to prevent this crash.
```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /usr/local/cozy/apps/data-system/build/server/lib/request.js:245:41
    at /usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:110:9)
    at /usr/local/cozy/apps/data-system/build/server/lib/request.js:244:24
    at recoverDocs (/usr/local/cozy/apps/data-system/build/server/lib/request.js:85:12)
    at Object.callback (/usr/local/cozy/apps/data-system/build/server/lib/request.js:82:14)
    at /usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/database/documents.js:52:18
```

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at removeEmptyView (/usr/local/cozy/apps/data-system/build/server/lib/request.js:191:16)
    at /usr/local/cozy/apps/data-system/build/server/lib/request.js:253:22
    at Object.async.each (/usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:107:20)
    at /usr/local/cozy/apps/data-system/build/server/lib/request.js:248:26
    at /usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/local/cozy/apps/data-system/node_modules/async/lib/async.js:110:9)
    at /usr/local/cozy/apps/data-system/build/server/lib/request.js:244:24
```

**Comment by poupotte** [comment]
This issue should be fixed with new version : v 2.1.9. Thanks @clochix !
