### ISSUE TITLE
cozy update crash on data-system update

### ISSUE THREAD

**Issue by 19emtuck** [cozy/cozy-data-system#213]
I just update recently my coz cloud and get stuck after data-system has been updated.
I checked logs (cat /usr/local/var/log/cozy/data-system.log-backup)

And it seems to be a dependency problem, then I checked americano and cozy-americano.
Both packages seems to be installed (also check them with an npm install -g)

so I'm stuck on it :(

Error: Cannot find module 'americano'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/local/cozy/apps/data-system/build/server.js:6:15)
    at Object.<anonymous> (/usr/local/cozy/apps/data-system/build/server.js:26:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

-----------------------------------------------------------------------------------------------------------------------
You'll also find below cozy-controller logs start

[2016-03-11 00:02:52:361] info - lib:autostart | ### AUTOSTART ###
[2016-03-11 00:02:52:512] info - lib:autostart | couchDB: started
[2016-03-11 00:02:52:592] info - lib:autostart | data-system: starting ...
[2016-03-11 00:02:52:781] info - lib:spawner | data-system: start with pid 15929
[2016-03-11 00:02:53:752] info - lib:spawner | data-system: restart with pid 15949
[2016-03-11 00:02:54:735] info - lib:spawner | data-system: restart with pid 15964
[2016-03-11 00:02:55:668] info - lib:spawner | data-system: restart with pid 15976
[2016-03-11 00:02:56:521] info - lib:spawner | data-system: restart with pid 15981
[2016-03-11 00:02:57:450] error - lib:spawner | Callback on Exit
[2016-03-11 00:02:57:456] error - lib:spawner | Callback on Exit
[2016-03-11 00:02:57:465] error - lib:autostart | data-system didn't start
[2016-03-11 00:02:57:468] error - lib:autostart | data-system didn't start
[2016-03-11 00:02:57:520] error - lib:autostart | Error: data-system CANT START
    at onExit (/usr/local/lib/node_modules/cozy-controller/build/server/lib/spawner.js:251:26)
    at listener (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:251:10)
    at EventEmitter.emit (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at letChildDie (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/lib/forever-monitor/monitor.js:199:12)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/lib/forever-monitor/monitor.js:213:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
[2016-03-11 00:02:57:544] error - lib:autostart | Error: data-system CANT START
    at onExit (/usr/local/lib/node_modules/cozy-controller/build/server/lib/spawner.js:251:26)
    at listener (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:251:10)
    at EventEmitter.emit (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at letChildDie (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/lib/forever-monitor/monitor.js:199:12)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cozy-controller/node_modules/cozy-forever-monitor/lib/forever-monitor/monitor.js:213:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
[2016-03-11 00:02:57:549] error - server | Error during autostart:
[2016-03-11 00:02:57:561] error - server | Error during autostart:
[Error: data-system didn't start]

**Comment by aenario** [comment]
Hi, americano should be installed as a dependency of the datas-sytem, so in `/usr/local/cozy/apps/data-system/node_modules/americano`

To install it, 
```
cd /usr/local/cozy/apps/data-system/
npm install
```

Note that it is different from `npm install americano -g`, which will install it the dependency in `$(npm config get prefix)/node_modules/americano`

Not sure about why it wasn't installed by the controller in the first place : could be a temporary failure of npm's server or there maybe something wrong with permissions. Do you have a particular setup or do you use the debian package ?

**Comment by 19emtuck** [comment]
ok got strange errors

npm ERR! Error: Attempt to unlock gm@1.21.1, which hasn't been locked
npm ERR!     at unlock (/opt/node/lib/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/opt/node/lib/node_modules/npm/lib/cache.js:646:5)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:655:20
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /opt/node/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.4.61+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/cozy/apps/data-system
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! Error: Attempt to unlock coffee-coverage@0.4.2, which hasn't been locked
npm ERR!     at unlock (/opt/node/lib/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/opt/node/lib/node_modules/npm/lib/cache.js:646:5)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:655:20
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /opt/node/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.4.61+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/cozy/apps/data-system
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! Error: Attempt to unlock http-proxy@1.12.0, which hasn't been locked
npm ERR!     at unlock (/opt/node/lib/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/opt/node/lib/node_modules/npm/lib/cache.js:646:5)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:655:20
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /opt/node/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.4.61+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/cozy/apps/data-system
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! Error: Attempt to unlock coffee-jshint@0.2.3, which hasn't been locked
npm ERR!     at unlock (/opt/node/lib/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/opt/node/lib/node_modules/npm/lib/cache.js:646:5)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:655:20
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /opt/node/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by 19emtuck** [comment]
Ok, I finally give up to fix this installation. I reinstall cozy

**Comment by frankrousseau** [comment]
It looks like the Cozy controller is no more started. Can you run:

    ps -ef | grep cozy-controller

?

**Comment by 19emtuck** [comment]
Finally I fully re-installed cozy. On IRC channel, they told me to update node espacially to aim node 4.0. I had other weird and side effects after node installation has been completed. For instance every application has to be installed manually, cozy says it was already installed. Which means :

- git clone
- cd
- npm install
- cd ..
- chown



So I did it, replace everything and reinstall fully cozy. 

It works actually :) so this issue should be closed.


So thx you and thank you fie the guys on IRC channel.

**Comment by 19emtuck** [comment]
finally I can say : cozy works on cubietruck with node 4.0

**Comment by frankrousseau** [comment]
Thank you @19emtuck for your patience and for testing Cozy + Node 4 on Cubietruck!
