### ISSUE TITLE
TypeError: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#229]
Seen in users logs:
```
error - lib/encryption | TypeError: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipher.Cipher.final (crypto.js:323:27)
    at CryptoTools.module.exports.CryptoTools.decrypt (/usr/local/cozy/apps/data-system/build/server/lib/crypto_tools.js:47:27)
    at Object.exports.decrypt (/usr/local/cozy/apps/data-system/build/server/lib/encryption.js:127:30)
    at Object.<anonymous> (/usr/local/cozy/apps/data-system/build/server/controllers/requests.js:73:50)
    at Response.collectionPrototype.forEach (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/response.js:107:19)
    at /usr/local/cozy/apps/data-system/build/server/controllers/requests.js:66:14
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:244:9)
    at Request.self.callback (/usr/local/cozy/apps/data-system/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1035:10)
```

DS version 2.5.5

**Comment by clochix** [comment]
`node_module` folder did belong to root, so npm wasn't able to update some dependencies.
