### ISSUE TITLE
TypeError: Cannot read property 'docType' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#237]
```
[2016-06-10 08:20:20:867] error - helper/db_feed | Error: connect EMFILE 127.0.0.1:5984 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:849:16)
    at net.js:984:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)
/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/lib/indexer.js:176
  docType = (ref = doc.docType) != null ? typeof ref.toLowerCase === "function" ? ref.toLowerCase() : void 0 : void 0;
                      ^

TypeError: Cannot read property 'docType' of undefined
    at Object.exports.onDocumentUpdate (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/lib/indexer.js:176:23)
    at Object.callback (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/lib/feed.js:193:19)
    at /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cradle/lib/cradle/database/documents.js:52:18
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cradle/lib/cradle.js:224:20)
    at self.callback (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
```

**Comment by nono** [comment]
I think I got the same with running the integration tests from cozy-desktop:

```
[2016-06-16 16:05:03:388] error - helper/db_feed | CouchError: not_found: deleted
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:241:29)
    at Request.self.callback (/usr/local/cozy/apps/data-system/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
[2016-06-16 16:05:03:388] error - helper/db_feed | CouchError: not_found: deleted
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:241:29)
    at Request.self.callback (/usr/local/cozy/apps/data-system/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
/usr/local/cozy/apps/data-system/build/server/lib/indexer.js:176
  docType = (ref = doc.docType) != null ? typeof ref.toLowerCase === "function" ? ref.toLowerCase() : void 0 : void 0;
                      ^

TypeError: Cannot read property 'docType' of undefined
    at Object.exports.onDocumentUpdate (/usr/local/cozy/apps/data-system/build/server/lib/indexer.js:176:23)
    at Object.callback (/usr/local/cozy/apps/data-system/build/server/lib/feed.js:188:19)
    at /usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle/database/documents.js:52:18
    at Request._onResponse [as _callback] (/usr/local/cozy/apps/data-system/node_modules/cradle/lib/cradle.js:241:20)
    at Request.self.callback (/usr/local/cozy/apps/data-system/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/cozy/apps/data-system/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```
