### ISSUE TITLE
Error trying to download a large folder

### ISSUE THREAD

**Issue by l-vincent-l** [cozy/cozy-data-system#245]
When I try to download a folder with a lot of files I have this error:

[2016-07-05 21:58:39:145] error - app:error | Error: connect ENOBUFS 127.0.0.1:5984 - Local (127.0.0.1:56431)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:986:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

I'm running it on a dev environment.

**Comment by clochix** [comment]
Hi @l-vincent-l, thanks for reporting!
Which version of Node.js is running on your server?

**Comment by l-vincent-l** [comment]
I'm running 4.2.6

**Comment by clochix** [comment]
4.2.6 should be fine.
Pinging @aenario
